### ISSUE TITLE
Why private key to encrypt?

### ISSUE THREAD

**Issue by filipniziol** [angelol/eos-encryption-demo#1]
Why to encrypt the data with someone's else public key one is required to use one's own private key as well?
How does it work, that when decrypting data one needs only one's private key and public key of the first person?
Is it possible to encrypt the data only with public key of the other party so that to decrypt the data only private key is required?

**Comment by angelol** [comment]
Please keep in mind that I didn't invent this method, Dan did. Please see his original Steem Post here:

https://steemit.com/steem/@dantheman/how-to-encrypt-a-memo-when-transferring-steem

Now to your questions:

> Why to encrypt the data with someone's else public key one is required to use one's own private key as well? How does it work, that when decrypting data one needs only one's private key and public key of the first person?

That's because the private key and public key are used to generate a shared secret that is then used to symmetrically encrypt the message. This method is called Elliptic Curve Integrated Encryption Scheme (ECIES). That's also what is implemented by the eosjs-ecc code.

> Is it possible to encrypt the data only with public key of the other party so that to decrypt the data only private key is required?

It probably is, but eosjs-ecc does not seem to implement it. I don't know the reason for it. However, in a blockchain, you're always gonna know who the sender of a message is, so you're gonna know the public key, so that shouldn't be a problem.

If you don't want to use this method, you could always have your users generate their own distinct symmetric keypair and register the public key with the contract.

**Comment by filipniziol** [comment]
Thank you for the answer!
